In [58]:
import numpy as np
import pandas as pd
import astropy.time
from Extend_Predictors import load_enso, load_independent_linear, load_qbo, load_solar
from datetime import datetime

In [3]:
columnStr = ['date', 'one', 'two']
tropop = pd.read_csv('/home/poyraden/MLR_Uccle/Files/newProxies/tropop.txt', header = None, sep = "\s *",
                     engine="python", names=columnStr)

In [4]:
columnStr = ['jdate', 'pressure', 'pressure_ano']
tropop = pd.read_csv('/home/poyraden/MLR_Uccle/Files/newProxies/tropop.txt', header = None, sep = "\s *",
                     engine="python", names=columnStr)

julian_dates = tropop['jdate'].tolist()
dates = [0]*len(julian_dates)

for d in range(len(julian_dates)):
    tmp = julian_dates[d]
    tmp = float(tmp)
    tmp = int(tmp)
    julian_dates[d] = int(tmp)

    dates[d] = astropy.time.Time(julian_dates[d]-14,format='jd')
    dates[d] = dates[d].iso
    dates[d] = pd.to_datetime(dates[d]).date()

tropop['date'] = dates
tropop['date'] = pd.to_datetime(tropop['date'], format='%Y-%m')
tropop.set_index('date', inplace=True)

tropop['tropop_pre'] = (tropop.pressure - np.nanmean(tropop.pressure))/np.nanstd(tropop.pressure)
#tropop['pressure_ano_nor'] = (tropop.two - np.nanmean(tropop.two))/np.nanstd(tropop.two)
tropop = tropop.drop(columns={'jdate','pressure', 'pressure_ano'})

print(len(tropop))
tropop[0:5]

565

            tropop_pre
date
1969-01-01   -0.088823
1969-02-01    3.087336
1969-03-01    0.865576
1969-04-01    0.393954
1969-05-01    1.260022

In [5]:
#   #   #   #   #   #
# Surface Temperature
#   #   #   #   #   #


columnStr = ['jdate', 'temp', 'ano']
tempsur = pd.read_csv('/home/poyraden/MLR_Uccle/Files/newProxies/tempsurf.txt', header = None, sep = "\s *",
                     engine="python", names=columnStr)

julian_dates = tempsur['jdate'].tolist()
dates = [0]*len(julian_dates)

for d in range(len(julian_dates)):
    tmp = julian_dates[d]
    tmp = float(tmp)
    tmp = int(tmp)
    julian_dates[d] = int(tmp)

    dates[d] = astropy.time.Time(julian_dates[d]-14,format='jd')
    dates[d] = dates[d].iso
    dates[d] = pd.to_datetime(dates[d]).date()

tempsur['date'] = dates
pd.to_datetime(tempsur['date'], format='%Y-%m')
tempsur.set_index('date', inplace=True)

tempsur['temp_nor'] = (tempsur.temp - np.nanmean(tempsur.temp))/np.nanstd(tempsur.temp)
#tempsur['tempano_nor'] = (tempsur.ano - np.nanmean(tempsur.ano))/np.nanstd(tempsur.ano)
tempsur = tempsur.drop(columns={'jdate','temp', 'ano'})
 
len(tempsur),tempsur[0:5]

(559,             temp_nor
 date
 1969-01-01 -1.105104
 1969-02-01 -1.718369
 1969-03-01 -1.388447
 1969-04-01 -0.358388
 1969-05-01  0.367698)

In [6]:
#   #   #   #   #   #
# AO 2018
#   #   #   #   #   #

columnStr = ['year', 'month', 'day','ao']
ao = pd.read_csv('/home/poyraden/MLR_Uccle/Files/newProxies/AO2018.txt', header = None, sep = "\s *",
                     engine="python", names=columnStr)
ao['date'] = pd.to_datetime(ao[['year', 'month', 'day']])
ao.set_index('date', inplace=True)
ao = ao.resample('MS').mean()

ao = ao.drop(columns={'year','month', 'day'})

ao['AO'] = (ao.ao - np.nanmean(ao.ao))/np.nanstd(ao.ao)
ao = ao.drop(columns = 'ao')
ao = ao.loc['1969-01-01':'2018-12-01'] # to have the same time period for all proxies
print(ao[0:10])

print(len(ao))

                  AO
date
1969-01-01 -2.859303
1969-02-01 -3.005423
1969-03-01 -1.474160
1969-04-01  0.546539
1969-05-01 -0.612228
1969-06-01 -0.239608
1969-07-01  0.517614
1969-08-01 -0.673604
1969-09-01  0.024653
1969-10-01  0.205619
600

In [7]:
#   #   #   #   #   #
# NOI
#   #   #   #   #   #
columnStr = ['date', 'what','noi']
noi = pd.read_csv('/home/poyraden/MLR_Uccle/Files/newProxies/NOI_NOAA2018.txt', header = None, sep = "\s *",
                     engine="python", names=columnStr)
noi['date'] = pd.to_datetime(noi['date'], format='%d-%b-%Y')
noi['date'] = noi['date'] - pd.offsets.MonthBegin(1, normalize=True)
noi.set_index('date', inplace=True)
noi = noi.drop(columns= 'what')
noi['noi_nor'] = (noi.noi - np.nanmean(noi.noi))/np.nanstd(noi.noi)
noi = noi.loc['1969-01-01':'2018-12-01']
noi[0:10]

len(noi)

600

In [8]:
#   #   #   #   #   #
# tele_index EA
#   #   #   #   #   #

columnStr = ['year', 'month', 'NAO', 'EA','WP', 'EP_NP','PNA', 'EA_WR',
             'SCA', 'TNH', 'POL', 'PT', 'Expl_Var']
tele = pd.read_csv('/home/poyraden/MLR_Uccle/Files/newProxies/tele_index.nh',
                   header = None, sep = "\s *",
                   engine="python", names=columnStr, skiprows = 19)
tele['day'] = len(tele) * [1]
tele['date'] = pd.to_datetime(tele[['year', 'month','day']])
tele.set_index('date', inplace=True)
tele = tele.drop(columns={'year','month', 'day'})

tele = tele.loc['1969-01-01':'2018-12-01'] # to have the same time period for all proxies
len(tele)

600

In [9]:
#   #   #   #   #   #
#AOD
#   #   #   #   #   #

columnStr = ['bdate', 'global_aod', 'north_aod', 'south_aod']
aod1 = pd.read_csv('/home/poyraden/MLR_Uccle/Files/teleconnection_indices/AOD.txt', header = None, sep = "\s *",
                   engine="python", names = columnStr)
aod1['date'] = pd.date_range(start='1850-01-01', end='2012-09-01', freq = 'MS')

aod1.set_index('date', inplace=True)
aod1 = aod1.drop(columns={'bdate'})

mean_glob = np.nanmean(aod1.loc['2009-01-01':'2012-09-01']['global_aod'].tolist())
mean_north = np.nanmean(aod1.loc['2009-01-01':'2012-09-01']['north_aod'].tolist())
mean_south = np.nanmean(aod1.loc['2009-01-01':'2012-09-01']['south_aod'].tolist())

aod2 = pd.DataFrame()
aod2['date'] = pd.date_range(start='2012-10-01', end='2018-12-01', freq = 'MS')
aod2['global_aod'] = [mean_glob] * len(aod2)
aod2['north_aod'] = [mean_north] * len(aod2)
aod2['south_aod'] = [mean_south] * len(aod2)

aod2.set_index('date', inplace=True)

frames = [aod1, aod2]
aod = pd.concat(frames)
aod = aod.loc['1969-01-01':'2018-12-01']

aod['global_nor'] = (aod.global_aod -  np.nanmean(aod.global_aod))/ np.nanstd(aod.global_aod)
aod['north_nor'] = (aod.north_aod -  np.nanmean(aod.north_aod))/ np.nanstd(aod.north_aod)
aod['south_nor'] = (aod.south_aod -  np.nanmean(aod.south_aod))/ np.nanstd(aod.south_aod)



len(aod),aod[0:5]

(600,
             global_aod  north_aod  south_aod  global_nor  north_nor  south_nor
 date
 1969-01-01      0.0429     0.0443     0.0414    1.195220   1.035035   1.329291
 1969-02-01      0.0414     0.0428     0.0400    1.132701   0.980911   1.264140
 1969-03-01      0.0398     0.0411     0.0384    1.066014   0.919571   1.189683
 1969-04-01      0.0383     0.0396     0.0370    1.003495   0.865447   1.124532
 1969-05-01      0.0367     0.0380     0.0354    0.936808   0.807715   1.050074)

In [11]:
#new_predictors = ao
new_predictors = tempsur
new_predictors['AO'] = ao.AO
new_predictors['pre_tropop'] = tropop['tropop_pre']
new_predictors['temp_sur'] = tempsur['temp_nor']
new_predictors['NOI'] = noi['noi_nor']
new_predictors['EA'] = tele['EA']
new_predictors['AOD'] = aod.global_nor

In [12]:

new_predictors[0:5], len(new_predictors)

(            temp_nor        AO  pre_tropop  temp_sur       NOI    EA       AOD
 date
 1969-01-01 -1.105104 -2.859303   -0.088823 -1.105104 -2.075709 -1.70  1.195220
 1969-02-01 -1.718369 -3.005423    3.087336 -1.718369 -2.179096 -0.52  1.132701
 1969-03-01 -1.388447 -1.474160    0.865576 -1.388447  0.541508  0.02  1.066014
 1969-04-01 -0.358388  0.546539    0.393954 -0.358388 -0.519546 -1.37  1.003495
 1969-05-01  0.367698 -0.612228    1.260022  0.367698 -0.787134  0.97  0.936808,
 559)

In [77]:
linear_trends = load_independent_linear(pre_trend_end='1997-01-01', post_trend_start='2000-01-01')
#print('linear trend', list(linear_trends))
enso = load_enso(lag_months= 0 )
#print('enso', type(enso), list(enso))
solar = load_solar()
#print('solar', type(solar),list(solar))
QBO = load_qbo(pca = 2)
#print('QBO', list(QBO))

ext_predictor = pd.DataFrame()

# extende solar dates
ex_dates = pd.date_range(start='2018-02', end='2018-12', freq = 'MS')

value = solar.loc['2018-01-01']['solar_mm']
values = [value] * len(ex_dates)
solar2 = pd.DataFrame(values, index= ex_dates, columns=['solar_mm'])
solar = solar.append(solar2)
solar['nor'] = (solar.solar_mm - np.mean(solar.solar_mm))/np.std(solar.solar_mm)
norsolar = solar.nor.tolist()

predictors_uccle = linear_trends
predictors_uccle['enso'] = enso
predictors_uccle.loc['2018-12']['enso'] = predictors_uccle.loc['2018-11']['enso']
predictors_uccle['qboA'] = (QBO.pca - QBO.pca.mean())/QBO.pca.std()
predictors_uccle['qboB'] = (QBO.pcb - QBO.pcb.mean())/QBO.pcb.std()
predictors_uccle['solar'] = norsolar

/home/poyraden/MLR_Uccle/Codes/Extend_Predictors.py:96: FutureWarning: read_table is deprecated, use read_csv instead.
  engine='python', header=None)

pgae https://omniweb.gsfc.nasa.gov/cgi/nx1.cgi?activity=retrieve&res=daily&spacecraft=omni2_daily&start_date=19690101&end_date=20180031&vars=50&scale=Linear&ymin=&ymax=&charsize=&symsize=0.5&symbol=0&imagex=640&imagey=480

In [79]:
predictors_uccle.index = predictors_uccle.index.to_timestamp()
predictors_uccle.index

DatetimeIndex(['1969-01-01', '1969-02-01', '1969-03-01', '1969-04-01',
               '1969-05-01', '1969-06-01', '1969-07-01', '1969-08-01',
               '1969-09-01', '1969-10-01',
               ...
               '2018-03-01', '2018-04-01', '2018-05-01', '2018-06-01',
               '2018-07-01', '2018-08-01', '2018-09-01', '2018-10-01',
               '2018-11-01', '2018-12-01'],
              dtype='datetime64[ns]', length=600, freq='MS')

In [80]:
predictors_uccle.index.date
#= predictors_uccle.index.date
#predictors_uccle.index.

array([datetime.date(1969, 1, 1), datetime.date(1969, 2, 1),
       datetime.date(1969, 3, 1), datetime.date(1969, 4, 1),
       datetime.date(1969, 5, 1), datetime.date(1969, 6, 1),
       datetime.date(1969, 7, 1), datetime.date(1969, 8, 1),
       datetime.date(1969, 9, 1), datetime.date(1969, 10, 1),
       datetime.date(1969, 11, 1), datetime.date(1969, 12, 1),
       datetime.date(1970, 1, 1), datetime.date(1970, 2, 1),
       datetime.date(1970, 3, 1), datetime.date(1970, 4, 1),
       datetime.date(1970, 5, 1), datetime.date(1970, 6, 1),
       datetime.date(1970, 7, 1), datetime.date(1970, 8, 1),
       datetime.date(1970, 9, 1), datetime.date(1970, 10, 1),
       datetime.date(1970, 11, 1), datetime.date(1970, 12, 1),
       datetime.date(1971, 1, 1), datetime.date(1971, 2, 1),
       datetime.date(1971, 3, 1), datetime.date(1971, 4, 1),
       datetime.date(1971, 5, 1), datetime.date(1971, 6, 1),
       datetime.date(1971, 7, 1), datetime.date(1971, 8, 1),
       datetime.date(1971, 9, 1), datetime.date(1971, 10, 1),
       datetime.date(1971, 11, 1), datetime.date(1971, 12, 1),
       datetime.date(1972, 1, 1), datetime.date(1972, 2, 1),
       datetime.date(1972, 3, 1), datetime.date(1972, 4, 1),
       datetime.date(1972, 5, 1), datetime.date(1972, 6, 1),
       datetime.date(1972, 7, 1), datetime.date(1972, 8, 1),
       datetime.date(1972, 9, 1), datetime.date(1972, 10, 1),
       datetime.date(1972, 11, 1), datetime.date(1972, 12, 1),
       datetime.date(1973, 1, 1), datetime.date(1973, 2, 1),
       datetime.date(1973, 3, 1), datetime.date(1973, 4, 1),
       datetime.date(1973, 5, 1), datetime.date(1973, 6, 1),
       datetime.date(1973, 7, 1), datetime.date(1973, 8, 1),
       datetime.date(1973, 9, 1), datetime.date(1973, 10, 1),
       datetime.date(1973, 11, 1), datetime.date(1973, 12, 1),
       datetime.date(1974, 1, 1), datetime.date(1974, 2, 1),
       datetime.date(1974, 3, 1), datetime.date(1974, 4, 1),
       datetime.date(1974, 5, 1), datetime.date(1974, 6, 1),
       datetime.date(1974, 7, 1), datetime.date(1974, 8, 1),
       datetime.date(1974, 9, 1), datetime.date(1974, 10, 1),
       datetime.date(1974, 11, 1), datetime.date(1974, 12, 1),
       datetime.date(1975, 1, 1), datetime.date(1975, 2, 1),
       datetime.date(1975, 3, 1), datetime.date(1975, 4, 1),
       datetime.date(1975, 5, 1), datetime.date(1975, 6, 1),
       datetime.date(1975, 7, 1), datetime.date(1975, 8, 1),
       datetime.date(1975, 9, 1), datetime.date(1975, 10, 1),
       datetime.date(1975, 11, 1), datetime.date(1975, 12, 1),
       datetime.date(1976, 1, 1), datetime.date(1976, 2, 1),
       datetime.date(1976, 3, 1), datetime.date(1976, 4, 1),
       datetime.date(1976, 5, 1), datetime.date(1976, 6, 1),
       datetime.date(1976, 7, 1), datetime.date(1976, 8, 1),
       datetime.date(1976, 9, 1), datetime.date(1976, 10, 1),
       datetime.date(1976, 11, 1), datetime.date(1976, 12, 1),
       datetime.date(1977, 1, 1), datetime.date(1977, 2, 1),
       datetime.date(1977, 3, 1), datetime.date(1977, 4, 1),
       datetime.date(1977, 5, 1), datetime.date(1977, 6, 1),
       datetime.date(1977, 7, 1), datetime.date(1977, 8, 1),
       datetime.date(1977, 9, 1), datetime.date(1977, 10, 1),
       datetime.date(1977, 11, 1), datetime.date(1977, 12, 1),
       datetime.date(1978, 1, 1), datetime.date(1978, 2, 1),
       datetime.date(1978, 3, 1), datetime.date(1978, 4, 1),
       datetime.date(1978, 5, 1), datetime.date(1978, 6, 1),
       datetime.date(1978, 7, 1), datetime.date(1978, 8, 1),
       datetime.date(1978, 9, 1), datetime.date(1978, 10, 1),
       datetime.date(1978, 11, 1), datetime.date(1978, 12, 1),
       datetime.date(1979, 1, 1), datetime.date(1979, 2, 1),
       datetime.date(1979, 3, 1), datetime.date(1979, 4, 1),
       datetime.date(1979, 5, 1), datetime.date(1979, 6, 1),
       datetime.date(1979, 7, 1), datetime.date(1979, 8, 1),
       datetime.date(1979, 9, 1), datetime.date(1979, 10, 1),
       datetime.date(1979, 11, 1), datetime.date(1979, 12, 1),
       datetime.date(1980, 1, 1), datetime.date(1980, 2, 1),
       datetime.date(1980, 3, 1), datetime.date(1980, 4, 1),
       datetime.date(1980, 5, 1), datetime.date(1980, 6, 1),
       datetime.date(1980, 7, 1), datetime.date(1980, 8, 1),
       datetime.date(1980, 9, 1), datetime.date(1980, 10, 1),
       datetime.date(1980, 11, 1), datetime.date(1980, 12, 1),
       datetime.date(1981, 1, 1), datetime.date(1981, 2, 1),
       datetime.date(1981, 3, 1), datetime.date(1981, 4, 1),
       datetime.date(1981, 5, 1), datetime.date(1981, 6, 1),
       datetime.date(1981, 7, 1), datetime.date(1981, 8, 1),
       datetime.date(1981, 9, 1), datetime.date(1981, 10, 1),
       datetime.date(1981, 11, 1), datetime.date(1981, 12, 1),
       datetime.date(1982, 1, 1), datetime.date(1982, 2, 1),
       datetime.date(1982, 3, 1), datetime.date(1982, 4, 1),
       datetime.date(1982, 5, 1), datetime.date(1982, 6, 1),
       datetime.date(1982, 7, 1), datetime.date(1982, 8, 1),
       datetime.date(1982, 9, 1), datetime.date(1982, 10, 1),
       datetime.date(1982, 11, 1), datetime.date(1982, 12, 1),
       datetime.date(1983, 1, 1), datetime.date(1983, 2, 1),
       datetime.date(1983, 3, 1), datetime.date(1983, 4, 1),
       datetime.date(1983, 5, 1), datetime.date(1983, 6, 1),
       datetime.date(1983, 7, 1), datetime.date(1983, 8, 1),
       datetime.date(1983, 9, 1), datetime.date(1983, 10, 1),
       datetime.date(1983, 11, 1), datetime.date(1983, 12, 1),
       datetime.date(1984, 1, 1), datetime.date(1984, 2, 1),
       datetime.date(1984, 3, 1), datetime.date(1984, 4, 1),
       datetime.date(1984, 5, 1), datetime.date(1984, 6, 1),
       datetime.date(1984, 7, 1), datetime.date(1984, 8, 1),
       datetime.date(1984, 9, 1), datetime.date(1984, 10, 1),
       datetime.date(1984, 11, 1), datetime.date(1984, 12, 1),
       datetime.date(1985, 1, 1), datetime.date(1985, 2, 1),
       datetime.date(1985, 3, 1), datetime.date(1985, 4, 1),
       datetime.date(1985, 5, 1), datetime.date(1985, 6, 1),
       datetime.date(1985, 7, 1), datetime.date(1985, 8, 1),
       datetime.date(1985, 9, 1), datetime.date(1985, 10, 1),
       datetime.date(1985, 11, 1), datetime.date(1985, 12, 1),
       datetime.date(1986, 1, 1), datetime.date(1986, 2, 1),
       datetime.date(1986, 3, 1), datetime.date(1986, 4, 1),
       datetime.date(1986, 5, 1), datetime.date(1986, 6, 1),
       datetime.date(1986, 7, 1), datetime.date(1986, 8, 1),
       datetime.date(1986, 9, 1), datetime.date(1986, 10, 1),
       datetime.date(1986, 11, 1), datetime.date(1986, 12, 1),
       datetime.date(1987, 1, 1), datetime.date(1987, 2, 1),
       datetime.date(1987, 3, 1), datetime.date(1987, 4, 1),
       datetime.date(1987, 5, 1), datetime.date(1987, 6, 1),
       datetime.date(1987, 7, 1), datetime.date(1987, 8, 1),
       datetime.date(1987, 9, 1), datetime.date(1987, 10, 1),
       datetime.date(1987, 11, 1), datetime.date(1987, 12, 1),
       datetime.date(1988, 1, 1), datetime.date(1988, 2, 1),
       datetime.date(1988, 3, 1), datetime.date(1988, 4, 1),
       datetime.date(1988, 5, 1), datetime.date(1988, 6, 1),
       datetime.date(1988, 7, 1), datetime.date(1988, 8, 1),
       datetime.date(1988, 9, 1), datetime.date(1988, 10, 1),
       datetime.date(1988, 11, 1), datetime.date(1988, 12, 1),
       datetime.date(1989, 1, 1), datetime.date(1989, 2, 1),
       datetime.date(1989, 3, 1), datetime.date(1989, 4, 1),
       datetime.date(1989, 5, 1), datetime.date(1989, 6, 1),
       datetime.date(1989, 7, 1), datetime.date(1989, 8, 1),
       datetime.date(1989, 9, 1), datetime.date(1989, 10, 1),
       datetime.date(1989, 11, 1), datetime.date(1989, 12, 1),
       datetime.date(1990, 1, 1), datetime.date(1990, 2, 1),
       datetime.date(1990, 3, 1), datetime.date(1990, 4, 1),
       datetime.date(1990, 5, 1), datetime.date(1990, 6, 1),
       datetime.date(1990, 7, 1), datetime.date(1990, 8, 1),
       datetime.date(1990, 9, 1), datetime.date(1990, 10, 1),
       datetime.date(1990, 11, 1), datetime.date(1990, 12, 1),
       datetime.date(1991, 1, 1), datetime.date(1991, 2, 1),
       datetime.date(1991, 3, 1), datetime.date(1991, 4, 1),
       datetime.date(1991, 5, 1), datetime.date(1991, 6, 1),
       datetime.date(1991, 7, 1), datetime.date(1991, 8, 1),
       datetime.date(1991, 9, 1), datetime.date(1991, 10, 1),
       datetime.date(1991, 11, 1), datetime.date(1991, 12, 1),
       datetime.date(1992, 1, 1), datetime.date(1992, 2, 1),
       datetime.date(1992, 3, 1), datetime.date(1992, 4, 1),
       datetime.date(1992, 5, 1), datetime.date(1992, 6, 1),
       datetime.date(1992, 7, 1), datetime.date(1992, 8, 1),
       datetime.date(1992, 9, 1), datetime.date(1992, 10, 1),
       datetime.date(1992, 11, 1), datetime.date(1992, 12, 1),
       datetime.date(1993, 1, 1), datetime.date(1993, 2, 1),
       datetime.date(1993, 3, 1), datetime.date(1993, 4, 1),
       datetime.date(1993, 5, 1), datetime.date(1993, 6, 1),
       datetime.date(1993, 7, 1), datetime.date(1993, 8, 1),
       datetime.date(1993, 9, 1), datetime.date(1993, 10, 1),
       datetime.date(1993, 11, 1), datetime.date(1993, 12, 1),
       datetime.date(1994, 1, 1), datetime.date(1994, 2, 1),
       datetime.date(1994, 3, 1), datetime.date(1994, 4, 1),
       datetime.date(1994, 5, 1), datetime.date(1994, 6, 1),
       datetime.date(1994, 7, 1), datetime.date(1994, 8, 1),
       datetime.date(1994, 9, 1), datetime.date(1994, 10, 1),
       datetime.date(1994, 11, 1), datetime.date(1994, 12, 1),
       datetime.date(1995, 1, 1), datetime.date(1995, 2, 1),
       datetime.date(1995, 3, 1), datetime.date(1995, 4, 1),
       datetime.date(1995, 5, 1), datetime.date(1995, 6, 1),
       datetime.date(1995, 7, 1), datetime.date(1995, 8, 1),
       datetime.date(1995, 9, 1), datetime.date(1995, 10, 1),
       datetime.date(1995, 11, 1), datetime.date(1995, 12, 1),
       datetime.date(1996, 1, 1), datetime.date(1996, 2, 1),
       datetime.date(1996, 3, 1), datetime.date(1996, 4, 1),
       datetime.date(1996, 5, 1), datetime.date(1996, 6, 1),
       datetime.date(1996, 7, 1), datetime.date(1996, 8, 1),
       datetime.date(1996, 9, 1), datetime.date(1996, 10, 1),
       datetime.date(1996, 11, 1), datetime.date(1996, 12, 1),
       datetime.date(1997, 1, 1), datetime.date(1997, 2, 1),
       datetime.date(1997, 3, 1), datetime.date(1997, 4, 1),
       datetime.date(1997, 5, 1), datetime.date(1997, 6, 1),
       datetime.date(1997, 7, 1), datetime.date(1997, 8, 1),
       datetime.date(1997, 9, 1), datetime.date(1997, 10, 1),
       datetime.date(1997, 11, 1), datetime.date(1997, 12, 1),
       datetime.date(1998, 1, 1), datetime.date(1998, 2, 1),
       datetime.date(1998, 3, 1), datetime.date(1998, 4, 1),
       datetime.date(1998, 5, 1), datetime.date(1998, 6, 1),
       datetime.date(1998, 7, 1), datetime.date(1998, 8, 1),
       datetime.date(1998, 9, 1), datetime.date(1998, 10, 1),
       datetime.date(1998, 11, 1), datetime.date(1998, 12, 1),
       datetime.date(1999, 1, 1), datetime.date(1999, 2, 1),
       datetime.date(1999, 3, 1), datetime.date(1999, 4, 1),
       datetime.date(1999, 5, 1), datetime.date(1999, 6, 1),
       datetime.date(1999, 7, 1), datetime.date(1999, 8, 1),
       datetime.date(1999, 9, 1), datetime.date(1999, 10, 1),
       datetime.date(1999, 11, 1), datetime.date(1999, 12, 1),
       datetime.date(2000, 1, 1), datetime.date(2000, 2, 1),
       datetime.date(2000, 3, 1), datetime.date(2000, 4, 1),
       datetime.date(2000, 5, 1), datetime.date(2000, 6, 1),
       datetime.date(2000, 7, 1), datetime.date(2000, 8, 1),
       datetime.date(2000, 9, 1), datetime.date(2000, 10, 1),
       datetime.date(2000, 11, 1), datetime.date(2000, 12, 1),
       datetime.date(2001, 1, 1), datetime.date(2001, 2, 1),
       datetime.date(2001, 3, 1), datetime.date(2001, 4, 1),
       datetime.date(2001, 5, 1), datetime.date(2001, 6, 1),
       datetime.date(2001, 7, 1), datetime.date(2001, 8, 1),
       datetime.date(2001, 9, 1), datetime.date(2001, 10, 1),
       datetime.date(2001, 11, 1), datetime.date(2001, 12, 1),
       datetime.date(2002, 1, 1), datetime.date(2002, 2, 1),
       datetime.date(2002, 3, 1), datetime.date(2002, 4, 1),
       datetime.date(2002, 5, 1), datetime.date(2002, 6, 1),
       datetime.date(2002, 7, 1), datetime.date(2002, 8, 1),
       datetime.date(2002, 9, 1), datetime.date(2002, 10, 1),
       datetime.date(2002, 11, 1), datetime.date(2002, 12, 1),
       datetime.date(2003, 1, 1), datetime.date(2003, 2, 1),
       datetime.date(2003, 3, 1), datetime.date(2003, 4, 1),
       datetime.date(2003, 5, 1), datetime.date(2003, 6, 1),
       datetime.date(2003, 7, 1), datetime.date(2003, 8, 1),
       datetime.date(2003, 9, 1), datetime.date(2003, 10, 1),
       datetime.date(2003, 11, 1), datetime.date(2003, 12, 1),
       datetime.date(2004, 1, 1), datetime.date(2004, 2, 1),
       datetime.date(2004, 3, 1), datetime.date(2004, 4, 1),
       datetime.date(2004, 5, 1), datetime.date(2004, 6, 1),
       datetime.date(2004, 7, 1), datetime.date(2004, 8, 1),
       datetime.date(2004, 9, 1), datetime.date(2004, 10, 1),
       datetime.date(2004, 11, 1), datetime.date(2004, 12, 1),
       datetime.date(2005, 1, 1), datetime.date(2005, 2, 1),
       datetime.date(2005, 3, 1), datetime.date(2005, 4, 1),
       datetime.date(2005, 5, 1), datetime.date(2005, 6, 1),
       datetime.date(2005, 7, 1), datetime.date(2005, 8, 1),
       datetime.date(2005, 9, 1), datetime.date(2005, 10, 1),
       datetime.date(2005, 11, 1), datetime.date(2005, 12, 1),
       datetime.date(2006, 1, 1), datetime.date(2006, 2, 1),
       datetime.date(2006, 3, 1), datetime.date(2006, 4, 1),
       datetime.date(2006, 5, 1), datetime.date(2006, 6, 1),
       datetime.date(2006, 7, 1), datetime.date(2006, 8, 1),
       datetime.date(2006, 9, 1), datetime.date(2006, 10, 1),
       datetime.date(2006, 11, 1), datetime.date(2006, 12, 1),
       datetime.date(2007, 1, 1), datetime.date(2007, 2, 1),
       datetime.date(2007, 3, 1), datetime.date(2007, 4, 1),
       datetime.date(2007, 5, 1), datetime.date(2007, 6, 1),
       datetime.date(2007, 7, 1), datetime.date(2007, 8, 1),
       datetime.date(2007, 9, 1), datetime.date(2007, 10, 1),
       datetime.date(2007, 11, 1), datetime.date(2007, 12, 1),
       datetime.date(2008, 1, 1), datetime.date(2008, 2, 1),
       datetime.date(2008, 3, 1), datetime.date(2008, 4, 1),
       datetime.date(2008, 5, 1), datetime.date(2008, 6, 1),
       datetime.date(2008, 7, 1), datetime.date(2008, 8, 1),
       datetime.date(2008, 9, 1), datetime.date(2008, 10, 1),
       datetime.date(2008, 11, 1), datetime.date(2008, 12, 1),
       datetime.date(2009, 1, 1), datetime.date(2009, 2, 1),
       datetime.date(2009, 3, 1), datetime.date(2009, 4, 1),
       datetime.date(2009, 5, 1), datetime.date(2009, 6, 1),
       datetime.date(2009, 7, 1), datetime.date(2009, 8, 1),
       datetime.date(2009, 9, 1), datetime.date(2009, 10, 1),
       datetime.date(2009, 11, 1), datetime.date(2009, 12, 1),
       datetime.date(2010, 1, 1), datetime.date(2010, 2, 1),
       datetime.date(2010, 3, 1), datetime.date(2010, 4, 1),
       datetime.date(2010, 5, 1), datetime.date(2010, 6, 1),
       datetime.date(2010, 7, 1), datetime.date(2010, 8, 1),
       datetime.date(2010, 9, 1), datetime.date(2010, 10, 1),
       datetime.date(2010, 11, 1), datetime.date(2010, 12, 1),
       datetime.date(2011, 1, 1), datetime.date(2011, 2, 1),
       datetime.date(2011, 3, 1), datetime.date(2011, 4, 1),
       datetime.date(2011, 5, 1), datetime.date(2011, 6, 1),
       datetime.date(2011, 7, 1), datetime.date(2011, 8, 1),
       datetime.date(2011, 9, 1), datetime.date(2011, 10, 1),
       datetime.date(2011, 11, 1), datetime.date(2011, 12, 1),
       datetime.date(2012, 1, 1), datetime.date(2012, 2, 1),
       datetime.date(2012, 3, 1), datetime.date(2012, 4, 1),
       datetime.date(2012, 5, 1), datetime.date(2012, 6, 1),
       datetime.date(2012, 7, 1), datetime.date(2012, 8, 1),
       datetime.date(2012, 9, 1), datetime.date(2012, 10, 1),
       datetime.date(2012, 11, 1), datetime.date(2012, 12, 1),
       datetime.date(2013, 1, 1), datetime.date(2013, 2, 1),
       datetime.date(2013, 3, 1), datetime.date(2013, 4, 1),
       datetime.date(2013, 5, 1), datetime.date(2013, 6, 1),
       datetime.date(2013, 7, 1), datetime.date(2013, 8, 1),
       datetime.date(2013, 9, 1), datetime.date(2013, 10, 1),
       datetime.date(2013, 11, 1), datetime.date(2013, 12, 1),
       datetime.date(2014, 1, 1), datetime.date(2014, 2, 1),
       datetime.date(2014, 3, 1), datetime.date(2014, 4, 1),
       datetime.date(2014, 5, 1), datetime.date(2014, 6, 1),
       datetime.date(2014, 7, 1), datetime.date(2014, 8, 1),
       datetime.date(2014, 9, 1), datetime.date(2014, 10, 1),
       datetime.date(2014, 11, 1), datetime.date(2014, 12, 1),
       datetime.date(2015, 1, 1), datetime.date(2015, 2, 1),
       datetime.date(2015, 3, 1), datetime.date(2015, 4, 1),
       datetime.date(2015, 5, 1), datetime.date(2015, 6, 1),
       datetime.date(2015, 7, 1), datetime.date(2015, 8, 1),
       datetime.date(2015, 9, 1), datetime.date(2015, 10, 1),
       datetime.date(2015, 11, 1), datetime.date(2015, 12, 1),
       datetime.date(2016, 1, 1), datetime.date(2016, 2, 1),
       datetime.date(2016, 3, 1), datetime.date(2016, 4, 1),
       datetime.date(2016, 5, 1), datetime.date(2016, 6, 1),
       datetime.date(2016, 7, 1), datetime.date(2016, 8, 1),
       datetime.date(2016, 9, 1), datetime.date(2016, 10, 1),
       datetime.date(2016, 11, 1), datetime.date(2016, 12, 1),
       datetime.date(2017, 1, 1), datetime.date(2017, 2, 1),
       datetime.date(2017, 3, 1), datetime.date(2017, 4, 1),
       datetime.date(2017, 5, 1), datetime.date(2017, 6, 1),
       datetime.date(2017, 7, 1), datetime.date(2017, 8, 1),
       datetime.date(2017, 9, 1), datetime.date(2017, 10, 1),
       datetime.date(2017, 11, 1), datetime.date(2017, 12, 1),
       datetime.date(2018, 1, 1), datetime.date(2018, 2, 1),
       datetime.date(2018, 3, 1), datetime.date(2018, 4, 1),
       datetime.date(2018, 5, 1), datetime.date(2018, 6, 1),
       datetime.date(2018, 7, 1), datetime.date(2018, 8, 1),
       datetime.date(2018, 9, 1), datetime.date(2018, 10, 1),
       datetime.date(2018, 11, 1), datetime.date(2018, 12, 1)], dtype=object)

In [81]:
datelist1 = new_predictors.index.tolist()
datelist2 = predictors_uccle.index.date.tolist()

d1 = [''] * len(datelist1); d2 = [''] * len(datelist2)
for d in range(len(datelist1)):
    d1[d] = datelist1[d].strftime('%Y-%m-%d')
for di in range(len(datelist2)):
    d2[di] = datelist2[di].strftime('%Y-%m-%d')
    
d1[0:10], d2[0:10]

(['1969-01-01',
  '1969-02-01',
  '1969-03-01',
  '1969-04-01',
  '1969-05-01',
  '1969-06-01',
  '1969-07-01',
  '1969-08-01',
  '1969-09-01',
  '1969-10-01'],
 ['1969-01-01',
  '1969-02-01',
  '1969-03-01',
  '1969-04-01',
  '1969-05-01',
  '1969-06-01',
  '1969-07-01',
  '1969-08-01',
  '1969-09-01',
  '1969-10-01'])

In [82]:
set1 = set(d1)
set2 = set(d2)
difference = set1.symmetric_difference(set2)
print(len(difference), difference)
difference = list(difference)
print(len(difference))
print(difference[0:10])

difdate = [0]* 41

for j in range(41):
    difdate[j] = datetime.strptime(difference[j], '%Y-%m-%d')


    
print(type(difdate[0]), type(predictors_uccle.index))

41 {'1984-12-01', '1984-08-01', '1984-09-01', '1983-06-01', '1984-03-01', '1984-02-01', '1978-04-01', '1986-09-01', '1985-01-01', '1981-07-01', '1986-12-01', '1984-07-01', '1983-07-01', '1987-01-01', '1970-04-01', '1986-11-01', '1983-12-01', '1970-03-01', '1978-05-01', '1980-07-01', '1984-04-01', '1980-09-01', '1984-06-01', '1984-01-01', '1983-02-01', '1986-07-01', '1981-08-01', '1980-12-01', '1980-10-01', '1981-01-01', '1983-05-01', '1984-05-01', '1983-11-01', '1983-03-01', '1986-10-01', '1970-02-01', '1986-08-01', '1981-09-01', '1970-01-01', '1983-10-01', '1983-04-01'}
41
['1984-12-01', '1984-08-01', '1984-09-01', '1983-06-01', '1984-03-01', '1984-02-01', '1978-04-01', '1986-09-01', '1985-01-01', '1981-07-01']
<class 'datetime.datetime'> <class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [68]:
predictors_uccle.loc['1969-01-01':'1969-10-01']

,linear_pre,linear_post,post_const,pre_const,gap_const,enso,qboA,qboB,solar
1969-01-01,-2.800057,0.0,0.0,1.0,0.0,0.670,1.259361,0.897587,0.594145
1969-02-01,-2.791570,0.0,0.0,1.0,0.0,0.849,1.132396,0.537626,0.672909
1969-03-01,-2.783904,0.0,0.0,1.0,0.0,0.458,1.322247,0.249722,1.087912
1969-04-01,-2.775416,0.0,0.0,1.0,0.0,0.622,1.437846,-0.268946,0.782558
1969-05-01,-2.767203,0.0,0.0,1.0,0.0,0.674,1.401092,-0.544063,0.612746
1969-06-01,-2.758715,0.0,0.0,1.0,0.0,0.801,1.306426,-0.793939,1.015524
1969-07-01,-2.750501,0.0,0.0,1.0,0.0,0.490,1.108783,-0.963954,0.447504
1969-08-01,-2.742014,0.0,0.0,1.0,0.0,0.212,0.952528,-1.110109,0.567432
1969-09-01,-2.733526,0.0,0.0,1.0,0.0,0.162,0.595290,-1.060162,0.396908
1969-10-01,-2.725313,0.0,0.0,1.0,0.0,0.496,0.181393,-1.034818,0.704282

In [83]:
print(predictors_uccle[0:5].index)
len(predictors_uccle)

DatetimeIndex(['1969-01-01', '1969-02-01', '1969-03-01', '1969-04-01',
               '1969-05-01'],
              dtype='datetime64[ns]', freq='MS')

600

In [84]:
predictors_uccle = predictors_uccle.drop(difdate)
len(predictors_uccle)

559

In [85]:
predictors_uccle['AO'] =  new_predictors.AO.tolist()

predictors_uccle['pre_tropop'] = new_predictors['pre_tropop'].tolist()
predictors_uccle['temp_sur'] = new_predictors['temp_sur'].tolist()

predictors_uccle['NOI'] = new_predictors['NOI'].tolist()
predictors_uccle['EA'] = new_predictors['EA'].tolist()
predictors_uccle['AOD'] = new_predictors['AOD'].tolist()


predictors_uccle

,linear_pre,linear_post,post_const,pre_const,gap_const,enso,qboA,qboB,solar,AO,pre_tropop,temp_sur,NOI,EA,AOD
1969-01-01,-2.800057,0.000000,0.0,1.0,0.0,0.670,1.259361,0.897587,0.594145,-2.859303,-0.088823,-1.105104,-2.075709,-1.70,1.195220
1969-02-01,-2.791570,0.000000,0.0,1.0,0.0,0.849,1.132396,0.537626,0.672909,-3.005423,3.087336,-1.718369,-2.179096,-0.52,1.132701
1969-03-01,-2.783904,0.000000,0.0,1.0,0.0,0.458,1.322247,0.249722,1.087912,-1.474160,0.865576,-1.388447,0.541508,0.02,1.066014
1969-04-01,-2.775416,0.000000,0.0,1.0,0.0,0.622,1.437846,-0.268946,0.782558,0.546539,0.393954,-0.358388,-0.519546,-1.37,1.003495
1969-05-01,-2.767203,0.000000,0.0,1.0,0.0,0.674,1.401092,-0.544063,0.612746,-0.612228,1.260022,0.367698,-0.787134,0.97,0.936808
1969-06-01,-2.758715,0.000000,0.0,1.0,0.0,0.801,1.306426,-0.793939,1.015524,-0.239608,-0.087054,0.677795,-0.872634,0.57,0.870122
1969-07-01,-2.750501,0.000000,0.0,1.0,0.0,0.490,1.108783,-0.963954,0.447504,0.517614,-0.857130,1.204349,0.171964,-0.10,0.807603
1969-08-01,-2.742014,0.000000,0.0,1.0,0.0,0.212,0.952528,-1.110109,0.567432,-0.673604,-0.281761,0.925358,-0.352481,-1.82,0.740916
1969-09-01,-2.733526,0.000000,0.0,1.0,0.0,0.162,0.595290,-1.060162,0.396908,0.024653,-1.189183,0.532095,-0.212963,-0.51,0.682565
1969-10-01,-2.725313,0.000000,0.0,1.0,0.0,0.496,0.181393,-1.034818,0.704282,0.205619,-1.906660,0.092091,-0.584654,0.54,0.615878
1969-11-01,-2.716825,0.000000,0.0,1.0,0.0,0.659,-0.319599,-0.891762,0.709720,0.433901,0.979661,-0.915242,-0.508456,-0.48,0.553359
1969-12-01,-2.708611,0.000000,0.0,1.0,0.0,0.417,-0.599397,-0.799225,0.405337,-1.747589,-0.568289,-1.972217,-0.779264,-2.81,0.486672
1970-05-01,-2.667269,0.000000,0.0,1.0,0.0,-0.099,-1.011696,0.352593,1.121198,0.638625,0.022542,0.735495,0.901393,-0.41,0.165742
1970-06-01,-2.658781,0.000000,0.0,1.0,0.0,-0.636,-0.795115,1.180764,0.855035,0.983437,-0.958700,1.356013,-0.063429,-0.03,0.103223
1970-07-01,-2.650568,0.000000,0.0,1.0,0.0,-1.055,-0.441014,1.590573,0.792113,0.246759,0.047300,0.876844,-0.148570,-0.46,0.049040
1970-08-01,-2.642080,0.000000,0.0,1.0,0.0,-1.007,-0.301097,1.765512,0.459671,-0.154505,-0.920611,0.947922,0.109717,-0.47,-0.000975
1970-09-01,-2.633593,0.000000,0.0,1.0,0.0,-1.251,-0.193434,1.885564,0.524157,0.137705,-1.489858,0.701971,0.736833,0.41,-0.050990
1970-10-01,-2.625379,0.000000,0.0,1.0,0.0,-1.088,0.372896,1.821339,0.581627,0.206288,-1.544316,-0.099705,-0.104926,-0.88,-0.092669
1970-11-01,-2.616892,0.000000,0.0,1.0,0.0,-1.074,0.769696,1.714082,0.824830,0.486436,0.111870,-0.780985,-1.129132,0.58,-0.130181
1970-12-01,-2.608678,0.000000,0.0,1.0,0.0,-1.203,1.247025,1.453107,0.597711,-0.291103,0.434038,-1.460491,0.330800,-1.89,-0.167692
1971-01-01,-2.600190,0.000000,0.0,1.0,0.0,-1.204,1.272186,0.946642,0.800994,-0.054632,1.042780,-1.321560,1.757820,1.72,-0.201035
1971-02-01,-2.591703,0.000000,0.0,1.0,0.0,-1.507,1.170800,0.529692,0.303068,-0.813835,-0.558994,-1.246937,2.574895,-1.26,-0.234379
1971-03-01,-2.584037,0.000000,0.0,1.0,0.0,-1.790,1.314141,0.229304,-0.208988,-0.982554,1.376420,-1.205354,1.316370,-1.59,-0.263554
1971-04-01,-2.575549,0.000000,0.0,1.0,0.0,-1.839,1.375580,-0.121175,-0.063459,-0.475355,0.152815,-0.451385,0.849521,-1.74,-0.288562
1971-05-01,-2.567335,0.000000,0.0,1.0,0.0,-1.429,1.273346,-0.592550,-0.175142,0.787298,-0.050008,0.860082,0.681741,-0.43,-0.313569
1971-06-01,-2.558848,0.000000,0.0,1.0,0.0,-1.420,1.179844,-0.737043,-0.337468,-0.560239,0.315917,0.542087,0.121522,-0.71,-0.334409
1971-07-01,-2.550634,0.000000,0.0,1.0,0.0,-1.207,1.248517,-1.184595,0.016743,-0.470413,-1.496479,1.154546,0.346540,-1.24,-0.355248
1971-08-01,-2.542147,0.000000,0.0,1.0,0.0,-1.213,0.911966,-1.145735,-0.076612,0.925635,-0.603839,1.004816,-0.206524,-1.68,-0.371920
1971-09-01,-2.533659,0.000000,0.0,1.0,0.0,-1.467,0.717526,-0.965201,-0.331976,0.261506,-1.299777,0.654909,0.228486,-2.12,-0.351081
1971-10-01,-2.525445,0.000000,0.0,1.0,0.0,-1.415,0.523806,-1.228333,-0.303321,1.292716,-1.661213,-0.005902,1.252335,-0.20,-0.367752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-07-01,-0.000000,1.649863,1.0,0.0,0.0,0.352,0.905907,-0.183243,-0.686391,0.192709,-0.817136,1.330386,0.572989,1.82,-0.415359
2016-08-01,-0.000000,1.658350,1.0,0.0,0.0,0.167,1.009931,-0.678018,-0.723384,0.580294,-1.286763,1.443369,0.090399,2.08,-0.415359
2016-09-01,-0.000000,1.666838,1.0,0.0,0.0,-0.118,0.973599,-0.837886,-0.688433,0.888944,-1.723198,1.333126,1.303491,3.48,-0.415359
2016-10-01,-0.000000,1.675052,1.0,0.0,0.0,-0.385,0.987150,-0.853937,-0.756180,-1.809232,0.194486,-0.121463,-0.743848,0.42,-0.415359
2016-11-01,-0.000000,1.683539,1.0,0.0,0.0,-0.209,1.045932,-0.966451,-0.944594,-0.502901,0.558824,-0.772281,-0.228346,-0.45,-0.415359
2016-12-01,-0.000000,1.691753,1.0,0.0,0.0,-0.110,1.087760,-1.104985,-1.033028,1.894496,-1.566490,-0.611269,0.848805,0.87,-0.415359
2017-01-01,-0.000000,1.700240,1.0,0.0,0.0,-0.052,0.926395,-1.176383,-0.987784,1.050058,0.404927,-1.477898,-0.625436,-1.15,-0.415359
2017-02-01,-0.000000,1.708728,1.0,0.0,0.0,-0.043,0.974348,-1.225595,-0.984445,0.447837,0.161884,-0.792750,-1.752313,0.58,-0.415359
2017-03-01,-0.000000,1.716394,1.0,0.0,0.0,-0.080,0.624895,-1.312705,-1.009392,1.492061,-0.549109,-0.126782,0.982242,1.03,-0.415359
2017-04-01,-0.000000,1.724881,1.0,0.0,0.0,0.744,-0.057798,-1.413256,-0.841263,0.019400,-0.205402,-0.133390,-0.357848,-0.62,-0.415359
2017-05-01,-0.000000,1.733095,1.0,0.0,0.0,1.445,-0.817646,-1.116886,-0.980512,-0.622095,-0.184906,0.981285,0.153361,0.54,-0.415359
2017-06-01,-0.000000,1.741583,1.0,0.0,0.0,1.039,-1.219862,-0.583746,-0.940042,0.509730,-0.794011,1.451427,-0.504878,2.03,-0.415359
2017-07-01,-0.000000,1.749796,1.0,0.0,0.0,0.456,-1.392171,-0.213223,-0.873031,0.742278,-0.313366,1.423222,0.452789,1.83,-0.415359
2017-08-01,-0.000000,1.758284,1.0,0.0,0.0,0.009,-1.458535,-0.130221,-0.879954,0.258098,-1.233484,1.517831,-0.265193,2.02,-0.415359
2017-09-01,-0.000000,1.766771,1.0,0.0,0.0,-0.478,-1.495484,-0.125778,-0.564436,-0.384388,-0.184906,0.834939,-0.091332,1.58,-0.415359
2017-10-01,-0.000000,1.774985,1.0,0.0,0.0,-0.568,-1.545508,0.082309,-0.965058,0.798268,-2.251999,0.532095,1.229082,0.62,-0.415359
2017-11-01,-0.000000,1.783473,1.0,0.0,0.0,-0.285,-1.348423,0.382029,-1.079792,0.030459,-0.571463,-0.692500,-0.471251,0.12,-0.415359
2017-12-01,-0.000000,1.791686,1.0,0.0,0.0,-0.576,-1.048627,0.759017,-1.107712,0.049087,0.394770,-1.128313,1.165047,-0.50,-0.415359
2018-01-01,-0.000000,1.800174,1.0,0.0,0.0,-0.623,-1.194263,0.694062,-1.143096,-0.172767,1.633747,-0.755358,0.912841,0.55,-0.415359
2018-02-01,-0.000000,1.808661,1.0,0.0,0.0,-0.731,-1.339998,0.338968,-1.143096,0.220691,2.224215,-1.663086,2.224669,-1.38,-0.415359
2018-03-01,-0.000000,1.816328,1.0,0.0,0.0,-0.502,-1.377324,0.433327,-1.143096,-0.939174,1.305412,-0.781952,-0.346042,-0.62,-0.415359
2018-04-01,-0.000000,1.824815,1.0,0.0,0.0,-0.432,-1.214758,0.948789,-1.143096,0.651884,0.783957,0.546117,0.343678,1.13,-0.415359
2018-05-01,-0.000000,1.833029,1.0,0.0,0.0,0.465,-0.878466,1.462241,-1.143096,1.287565,-0.588376,1.202898,-0.120667,-0.07,-0.415359
2018-06-01,-0.000000,1.841516,1.0,0.0,0.0,0.469,-0.145430,1.878382,-1.143096,0.487956,-1.559552,1.520893,0.215250,-0.54,-0.415359
2018-07-01,-0.000000,1.849730,1.0,0.0,0.0,0.076,0.385182,1.836901,-1.143096,0.719768,-0.688994,2.274056,0.404852,2.36,-0.415359
2018-08-01,-0.000000,1.858217,1.0,0.0,0.0,0.132,0.804669,1.743307,-1.143096,0.944064,-0.452526,1.574886,0.147637,1.82,-0.415359
2018-09-01,-0.000000,1.866705,1.0,0.0,0.0,0.509,1.185663,1.342924,-1.143096,0.692598,-1.580138,1.016743,0.169459,0.15,-0.415359
2018-10-01,-0.000000,1.874919,1.0,0.0,0.0,0.468,1.351891,0.933160,-1.143096,0.520758,-1.780830,0.472944,-0.263047,-0.39,-0.415359
2018-11-01,-0.000000,1.883406,1.0,0.0,0.0,0.698,1.646219,0.401344,-1.143096,-1.008266,0.706464,-0.454447,-0.049477,0.32,-0.415359
2018-12-01,-0.000000,1.891620,1.0,0.0,0.0,0.698,1.642771,-0.093206,-1.143096,0.217761,-0.024298,-0.772442,0.866692,1.44,-0.415359

In [ ]:
#predictors_uccle['date'] =  pd.to_datetime(predictors_uccle.index, format='%Y-%d-%m')

predictors_uccle[0:2]

In [ ]:
new_predictors['date'] =  new_predictors.index
new_predictors['date'] = pd.datetime(new_predictors['date'], format = '%Y-%m')
tropop['date'] = pd.to_datetime(tropop['date'], format='%Y-%m')

In [ ]:
a = pd.DataFrame()
a['dummy'] = [1]*600
#newnew.set_index = new_predictors.index
a['AO'] = new_predictors['AO'].tolist()
a[0:5]

In [ ]:
len(new_predictors), len(predictors_uccle)
#newnew['solar'] = predictors_uccle['solar'].tolist()

dfs = [predictors_uccle, new_predictors]
all = pd.concat(dfs)

In [ ]:
all

In [97]:
allp = pd.read_csv('/home/poyraden/MLR_Uccle/Files/NewPredictors_ilt.csv')
len(allp)
allp[0:2]
datep = allp['Unnamed: 0'].tolist()
setp = set(datep)

In [110]:
uccle = pd.read_csv('/home/poyraden/MLR_Uccle/Files/1km_monthlymean_all_relative.csv')
len(uccle)
setu = set(uccle.date.tolist())
uccle.set_index('date', inplace=True)
uccle.index

Index(['1969-01-01', '1969-02-01', '1969-03-01', '1969-04-01', '1969-05-01',
       '1969-06-01', '1969-07-01', '1969-08-01', '1969-09-01', '1969-10-01',
       ...
       '2018-03-01', '2018-04-01', '2018-05-01', '2018-06-01', '2018-07-01',
       '2018-08-01', '2018-09-01', '2018-10-01', '2018-11-01', '2018-12-01'],
      dtype='object', name='date', length=600)

In [111]:
difup = setp.symmetric_difference(setu)
diup = list(difup)
print(diup[0:10])

['1984-12-01', '1984-08-01', '1984-09-01', '1983-06-01', '1984-03-01', '1984-02-01', '1978-04-01', '1986-09-01', '1985-01-01', '1981-07-01']

In [109]:
uccle[0:3]

,date,0km,1km,2km,3km,4km,5km,6km,7km,8km,...,26km_ds,27km_ds,28km_ds,29km_ds,30km_ds,31km_ds,32km_ds,33km_ds,34km_ds,35km_ds
0,1969-01-01,2.912,2.989,3.170,3.050,2.810,2.582,2.356,1.948,1.794,...,0.176023,0.150776,0.143983,0.164397,0.279994,0.490394,0.616999,0.726390,0.684176,NaN
1,1969-02-01,2.508,1.944,1.801,1.997,2.016,1.823,2.131,2.838,4.030,...,0.134114,0.164925,0.228390,0.269485,0.244483,0.311861,0.397392,0.462365,0.463972,0.441237
2,1969-03-01,1.832,2.352,3.002,3.077,2.906,2.517,2.097,1.852,1.843,...,-0.006758,-0.002138,-0.035659,-0.016093,0.018245,0.051473,0.096090,0.156548,0.142154,0.249384

In [112]:
uccle = uccle.drop(diup)

In [113]:
len(uccle)

559

In [116]:
a = {1,2,3,4,5,20,30,40}
b = {20,30,40, 100, 200}
print(a.difference(b))
print(b.difference(a))

{1, 2, 3, 4, 5}
{200, 100}