In [169]:
import pandas as pd  
import numpy as np  
from datetime import datetime
import astropy.time
import dateutil.parser

In [172]:
df = pd.read_csv('/home/poyraden/MLR_Uccle/Files/IAGOS_vertprof.txt',  sep = "\s *", engine="python")


julian_dates = df.columns.tolist()
julian_dates = julian_dates[1:]
print(julian_dates[0], type(julian_dates[0]))
dates = [0]*len(julian_dates)

for d in range(len(julian_dates)):
    tmp = julian_dates[d] 
    tmp = float(tmp)
    tmp = int(tmp)
    julian_dates[d] = int(tmp)

    dates[d] = astropy.time.Time(julian_dates[d],format='jd')
    dates[d] = dates[d].iso
    dates[d] = pd.to_datetime(dates[d]).date()

print(dates[:20])

df = df.drop(columns='-9999.0')
df.columns = dates
print(df.index.tolist())
#df = df.drop(df.index[12], df.index[13], df.index[14], df.index[15], df.index[16], df.index[17], df.index[18], df.index[19])
df = df.drop(df.index[12:36])
df

2449580.0 <class 'str'>
[datetime.date(1994, 8, 15), datetime.date(1994, 9, 15), datetime.date(1994, 10, 15), datetime.date(1994, 11, 15), datetime.date(1994, 12, 15), datetime.date(1995, 1, 15), datetime.date(1995, 2, 15), datetime.date(1995, 3, 15), datetime.date(1995, 4, 15), datetime.date(1995, 5, 15), datetime.date(1995, 6, 15), datetime.date(1995, 7, 15), datetime.date(1995, 8, 15), datetime.date(1995, 9, 15), datetime.date(1995, 10, 15), datetime.date(1995, 11, 15), datetime.date(1995, 12, 15), datetime.date(1996, 1, 15), datetime.date(1996, 2, 15), datetime.date(1996, 3, 15)]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

,1994-08-15,1994-09-15,1994-10-15,1994-11-15,1994-12-15,1995-01-15,1995-02-15,1995-03-15,1995-04-15,1995-05-15,...,2018-02-15,2018-03-15,2018-04-15,2018-05-15,2018-06-15,2018-07-15,2018-08-15,2018-09-15,2018-10-15,2018-11-15
0,2.701,3.029,2.304,1.300,1.810,2.048,2.181,2.874,2.822,4.010,...,2.390,-9999.0,-9999.0,-9999.0,3.768,-9999.0,-9999.0,4.848,3.466,-9999.0
1,3.101,3.515,2.930,2.560,2.858,2.746,2.872,3.251,3.621,4.650,...,2.916,-9999.0,-9999.0,-9999.0,3.477,-9999.0,-9999.0,4.527,3.883,-9999.0
2,3.627,3.334,2.835,2.760,2.904,2.738,2.900,3.124,3.725,4.052,...,2.906,-9999.0,-9999.0,-9999.0,3.319,-9999.0,-9999.0,2.999,3.502,-9999.0
3,3.584,3.262,2.895,2.565,2.669,2.629,2.769,2.794,3.563,3.735,...,2.777,-9999.0,-9999.0,-9999.0,3.671,-9999.0,-9999.0,3.058,3.040,-9999.0
4,3.315,3.134,2.657,2.475,2.324,2.367,2.515,2.632,3.270,3.463,...,2.811,-9999.0,-9999.0,-9999.0,2.595,-9999.0,-9999.0,2.961,3.423,-9999.0
5,2.986,2.710,2.332,2.166,1.997,2.146,2.247,2.461,2.886,2.971,...,2.743,-9999.0,-9999.0,-9999.0,3.650,-9999.0,-9999.0,2.729,3.237,-9999.0
6,2.557,2.445,1.989,1.794,1.724,1.874,1.979,2.269,2.578,2.630,...,2.325,-9999.0,-9999.0,-9999.0,2.359,-9999.0,-9999.0,2.245,2.376,-9999.0
7,2.515,2.211,1.750,1.630,1.560,1.784,1.935,2.644,2.466,2.319,...,4.223,-9999.0,-9999.0,-9999.0,4.115,-9999.0,-9999.0,2.236,2.411,-9999.0
8,2.472,2.070,1.588,1.347,1.508,1.840,2.214,3.882,2.334,2.328,...,-9999.000,-9999.0,-9999.0,-9999.0,3.578,-9999.0,-9999.0,1.640,2.586,-9999.0
9,2.547,2.068,1.638,1.224,1.551,2.619,3.287,4.811,2.490,2.871,...,5.981,-9999.0,-9999.0,-9999.0,2.894,-9999.0,-9999.0,1.424,2.862,-9999.0
10,2.989,2.185,2.336,1.360,1.604,3.810,5.324,5.742,3.908,3.568,...,8.019,-9999.0,-9999.0,-9999.0,4.755,-9999.0,-9999.0,1.171,3.326,-9999.0
11,3.999,3.521,2.583,2.398,2.757,4.990,4.350,7.533,4.044,6.179,...,10.811,-9999.0,-9999.0,-9999.0,-9999.000,-9999.0,-9999.0,2.186,2.497,-9999.0

In [173]:
dfT = df.T
dfT.columns
columns_ds = ['']*12
for c in range(12):
    columns_ds[c] =  str(c)+'km'
dfT.columns = columns_ds
#dfT.index =  pd.to_datetime(dfT.index, format='%Y-%m')

In [174]:
dfT

,0km,1km,2km,3km,4km,5km,6km,7km,8km,9km,10km,11km
1994-08-15,2.701,3.101,3.627,3.584,3.315,2.986,2.557,2.515,2.472,2.547,2.989,3.999
1994-09-15,3.029,3.515,3.334,3.262,3.134,2.710,2.445,2.211,2.070,2.068,2.185,3.521
1994-10-15,2.304,2.930,2.835,2.895,2.657,2.332,1.989,1.750,1.588,1.638,2.336,2.583
1994-11-15,1.300,2.560,2.760,2.565,2.475,2.166,1.794,1.630,1.347,1.224,1.360,2.398
1994-12-15,1.810,2.858,2.904,2.669,2.324,1.997,1.724,1.560,1.508,1.551,1.604,2.757
1995-01-15,2.048,2.746,2.738,2.629,2.367,2.146,1.874,1.784,1.840,2.619,3.810,4.990
1995-02-15,2.181,2.872,2.900,2.769,2.515,2.247,1.979,1.935,2.214,3.287,5.324,4.350
1995-03-15,2.874,3.251,3.124,2.794,2.632,2.461,2.269,2.644,3.882,4.811,5.742,7.533
1995-04-15,2.822,3.621,3.725,3.563,3.270,2.886,2.578,2.466,2.334,2.490,3.908,4.044
1995-05-15,4.010,4.650,4.052,3.735,3.463,2.971,2.630,2.319,2.328,2.871,3.568,6.179
1995-06-15,3.311,3.665,3.700,3.721,3.488,3.212,3.059,2.859,3.405,4.740,7.165,6.323
1995-07-15,4.120,4.343,4.014,3.931,3.703,3.647,3.276,2.909,2.645,2.760,3.263,3.358
1995-08-15,4.168,4.342,3.980,3.598,3.283,3.067,2.628,2.503,2.304,2.602,2.512,5.452
1995-09-15,2.219,2.838,2.974,2.992,2.562,2.429,2.234,1.927,2.255,2.399,2.941,3.307
1995-10-15,1.813,2.770,3.021,2.688,2.382,2.042,1.788,1.517,1.372,1.272,2.011,1.527
1995-11-15,1.330,2.414,2.687,2.559,2.341,2.045,1.761,1.558,1.366,1.357,1.920,2.706
1995-12-15,0.841,1.977,2.336,2.462,2.239,2.074,1.850,1.623,1.540,1.675,1.448,2.615
1996-01-15,1.641,3.255,2.963,2.657,2.440,2.112,1.812,1.592,1.351,1.357,1.611,3.296
1996-02-15,2.136,2.754,2.798,2.636,2.444,2.248,1.982,2.165,2.294,3.507,4.563,5.007
1996-03-15,3.508,4.216,3.624,3.324,3.109,2.827,2.569,2.398,2.327,3.134,3.871,-9999.000
1996-04-15,5.110,5.138,4.149,3.431,3.266,2.801,2.533,2.307,2.150,4.534,5.926,-9999.000
1996-05-15,4.072,3.975,3.761,3.690,3.407,3.156,2.945,2.607,2.576,3.864,5.436,9.293
1996-06-15,3.958,4.034,4.010,3.918,3.533,3.262,3.017,2.816,3.588,4.185,3.495,3.480
1996-07-15,3.487,4.222,3.695,3.488,3.341,3.084,2.922,2.927,3.182,3.637,4.132,4.693
1996-08-15,3.570,4.086,3.962,3.931,3.801,3.416,2.848,2.651,2.571,3.018,3.650,4.246
1996-09-15,2.328,2.981,3.293,3.297,3.067,2.808,2.479,2.277,2.042,2.251,2.407,2.714
1996-10-15,2.130,3.014,3.323,2.987,2.634,2.350,2.113,1.970,1.551,1.466,2.410,2.667
1996-11-15,1.601,2.577,2.705,2.642,2.376,2.198,2.081,2.055,1.986,3.201,4.109,4.135
1996-12-15,1.468,2.871,2.854,2.633,2.423,2.250,2.005,1.570,1.382,1.354,1.982,3.196
1997-01-15,1.694,3.079,2.885,2.690,2.442,2.171,1.919,1.738,1.723,1.479,2.253,1.822
...,...,...,...,...,...,...,...,...,...,...,...,...
2016-06-15,4.204,4.304,3.944,3.929,3.587,3.484,3.503,3.227,3.205,3.878,5.141,7.723
2016-07-15,4.059,3.950,3.468,3.554,3.381,3.113,2.968,2.901,2.666,3.447,4.483,4.623
2016-08-15,3.745,4.025,3.488,3.304,3.111,2.981,3.075,3.146,3.484,3.589,4.317,4.016
2016-09-15,4.218,4.480,3.558,3.172,3.080,2.800,2.699,2.281,1.773,1.721,1.389,1.877
2016-10-15,2.583,3.318,3.229,3.252,2.899,2.466,2.093,1.924,1.857,2.407,3.001,2.932
2016-11-15,2.630,3.430,3.171,3.189,2.861,2.632,2.430,2.143,1.825,2.051,3.131,6.927
2016-12-15,2.562,3.718,3.459,3.072,2.645,2.294,2.040,1.776,1.567,1.341,1.245,2.147
2017-01-15,2.936,3.427,3.174,2.937,2.611,2.323,2.205,2.268,2.481,3.128,3.524,8.610
2017-02-15,2.930,3.461,3.376,3.075,2.844,2.639,2.342,2.198,2.426,2.672,3.315,6.292
2017-03-15,3.219,3.834,3.313,3.181,3.117,2.789,2.382,2.179,2.432,2.874,3.710,5.726
2017-04-15,3.605,4.023,3.749,3.603,3.418,3.082,2.924,2.886,2.817,3.473,5.680,5.909
2017-05-15,4.455,4.554,3.809,3.496,3.105,2.987,2.898,2.550,2.217,2.557,2.938,5.004
2017-06-15,4.066,4.051,3.843,3.302,3.327,3.016,2.916,2.878,2.779,2.634,3.713,5.768
2017-07-15,4.129,4.164,3.545,3.226,3.257,3.046,2.980,2.983,3.711,4.221,4.070,4.964
2017-08-15,3.688,3.839,3.463,3.464,3.390,3.236,2.843,2.651,2.407,2.605,4.382,2.604
2017-09-15,2.993,3.722,3.637,3.306,3.133,2.972,2.744,2.333,2.397,2.794,4.986,3.769
2017-10-15,2.820,3.526,3.328,3.286,3.023,3.131,2.376,2.054,1.966,1.889,2.140,1.969
2017-11-15,2.535,3.436,3.307,2.920,2.607,2.280,2.025,1.763,1.467,1.701,1.717,1.716
2017-12-15,2.028,3.125,3.176,2.952,2.622,2.179,1.831,1.657,1.469,1.257,1.467,0.991
2018-01-15,2.746,3.149,3.144,3.080,2.590,2.198,1.954,2.249,2.747,4.180,3.648,5.145
2018-02-15,2.390,2.916,2.906,2.777,2.811,2.743,2.325,4.223,-9999.000,5.981,8.019,10.811
2018-03-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
2018-04-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
2018-05-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
2018-06-15,3.768,3.477,3.319,3.671,2.595,3.650,2.359,4.115,3.578,2.894,4.755,-9999.000
2018-07-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
2018-08-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
2018-09-15,4.848,4.527,2.999,3.058,2.961,2.729,2.245,2.236,1.640,1.424,1.171,2.186
2018-10-15,3.466,3.883,3.502,3.040,3.423,3.237,2.376,2.411,2.586,2.862,3.326,2.497
2018-11-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000

In [148]:
debilt = pd.read_csv('/home/poyraden/MLR_Uccle/Files/DeBilt_1km_monthlymean_reltropop_deas_relative.csv')
debilt[0:10]

,date,-11km_ds,-10km_ds,-9km_ds,-8km_ds,-7km_ds,-6km_ds,-5km_ds,-4km_ds,-3km_ds,...,15km_ds,16km_ds,17km_ds,18km_ds,19km_ds,20km_ds,21km_ds,22km_ds,23km_ds,24km_ds
0,1992-12-15,0.001163,0.049103,0.111862,0.058244,0.049103,0.059944,0.053087,0.019095,0.113195,...,0.214838,0.252348,0.275862,0.358164,0.359859,0.221279,0.237008,0.182354,0.262995,NaN
1,1993-01-15,0.126044,0.034049,-0.042350,-0.123432,-0.154443,-0.162674,-0.175789,-0.185304,-0.200784,...,-0.043545,-0.084040,-0.103013,-0.121851,-0.165918,-0.174724,-0.144133,-0.323052,NaN,NaN
2,1993-02-15,0.133973,0.145398,-0.004492,0.042599,0.140035,0.026629,-0.010353,0.001672,0.012799,...,-0.167331,-0.192523,-0.178567,-0.118330,-0.100400,-0.081429,-0.075123,-0.085866,NaN,NaN
3,1993-03-15,-0.118924,-0.016583,-0.034980,-0.035127,0.030819,-0.002227,-0.016076,0.014324,0.096976,...,0.141893,0.163336,0.151902,0.179814,0.190015,0.215907,0.199102,0.194537,0.145495,0.090326
4,1993-04-15,0.201104,0.137842,-0.017171,-0.041992,0.106109,-0.001566,-0.047518,-0.112805,-0.160315,...,-0.045867,-0.065495,-0.118241,-0.180258,-0.198195,-0.223823,-0.237535,0.010185,-0.076957,-0.172261
5,1993-05-15,-0.054243,0.105110,0.109285,-0.036587,-0.090780,-0.040732,-0.071362,-0.152899,-0.130227,...,0.062621,-0.011303,-0.051821,-0.068987,-0.116505,-0.167809,-0.215163,-0.290519,0.106649,NaN
6,1993-06-15,0.154439,0.079022,0.075681,-0.041140,-0.109061,-0.087529,-0.045067,-0.047129,-0.006975,...,0.028003,0.004651,0.002754,0.007345,0.005540,-0.003242,-0.031013,0.028443,-0.016958,-0.159843
7,1993-07-15,-0.455637,-0.348444,-0.253723,-0.112959,-0.164268,-0.138018,-0.140226,-0.172240,-0.188243,...,0.098116,0.067582,0.057626,0.077061,0.047082,0.061548,0.064200,0.014198,NaN,NaN
8,1993-08-15,0.084624,-0.266604,-0.322477,-0.286812,-0.160653,-0.103630,-0.336637,-0.263758,-0.257672,...,0.084248,0.104061,0.108253,0.089172,0.107521,0.043130,0.165038,NaN,NaN,NaN
9,1993-09-15,-0.229980,0.002869,0.099179,0.171754,0.250294,0.306249,0.254446,0.274891,0.517734,...,0.266315,0.230948,0.171624,0.033977,0.098556,NaN,NaN,NaN,NaN,NaN

In [179]:
uccle = pd.read_csv('/home/poyraden/MLR_Uccle/Files/IAGOS_1km_monthlymean.csv')

In [180]:
uccle[-20:]

,Unnamed: 0,0km,1km,2km,3km,4km,5km,6km,7km,8km,9km,10km,11km
272,2017-04-15,3.605,4.023,3.749,3.603,3.418,3.082,2.924,2.886,2.817,3.473,5.680,5.909
273,2017-05-15,4.455,4.554,3.809,3.496,3.105,2.987,2.898,2.550,2.217,2.557,2.938,5.004
274,2017-06-15,4.066,4.051,3.843,3.302,3.327,3.016,2.916,2.878,2.779,2.634,3.713,5.768
275,2017-07-15,4.129,4.164,3.545,3.226,3.257,3.046,2.980,2.983,3.711,4.221,4.070,4.964
276,2017-08-15,3.688,3.839,3.463,3.464,3.390,3.236,2.843,2.651,2.407,2.605,4.382,2.604
277,2017-09-15,2.993,3.722,3.637,3.306,3.133,2.972,2.744,2.333,2.397,2.794,4.986,3.769
278,2017-10-15,2.820,3.526,3.328,3.286,3.023,3.131,2.376,2.054,1.966,1.889,2.140,1.969
279,2017-11-15,2.535,3.436,3.307,2.920,2.607,2.280,2.025,1.763,1.467,1.701,1.717,1.716
280,2017-12-15,2.028,3.125,3.176,2.952,2.622,2.179,1.831,1.657,1.469,1.257,1.467,0.991
281,2018-01-15,2.746,3.149,3.144,3.080,2.590,2.198,1.954,2.249,2.747,4.180,3.648,5.145
282,2018-02-15,2.390,2.916,2.906,2.777,2.811,2.743,2.325,4.223,-9999.000,5.981,8.019,10.811
283,2018-03-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
284,2018-04-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
285,2018-05-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
286,2018-06-15,3.768,3.477,3.319,3.671,2.595,3.650,2.359,4.115,3.578,2.894,4.755,-9999.000
287,2018-07-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
288,2018-08-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000
289,2018-09-15,4.848,4.527,2.999,3.058,2.961,2.729,2.245,2.236,1.640,1.424,1.171,2.186
290,2018-10-15,3.466,3.883,3.502,3.040,3.423,3.237,2.376,2.411,2.586,2.862,3.326,2.497
291,2018-11-15,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000,-9999.000